language: node_js
cache:
  bundler: true
  directories:
  - $HOME/.yarn-cache
node_js:
- '6'
install:
  - npm install -g yarn
  - yarn install --pure-lockfile
script:
  - yarn test
after_success:
- bash deploy_docs.sh
deploy:
  provider: npm
  email: technik@propertybase.com
  api_key:
    secure: EQK2P3RyD0wJ9Y9DQQluVokvPrZlSrOa92m9jRq9SnoQoZTPKDPGC6gJgViih2GD7DOSQuinzyCg7LRHNMMuvwWc2rFWFZYEfcoeFggDDqChHcRMNJdI42SU2CLm6AZ+p7vnxK8mBR7rhJCKWUCehcnfDyESYgmHew11jAlbqa4Jujmzg0ZWwc04RdGL6haLJ5PVySnY12pQsxbhaLH9ETWJavA0ApVnVbbuNhUouybof21mN4bWIqNUZlblXwiA9aPyX28Fct6a633Qgxp/dHq/fp9u61LF4SbAFFAwr7fdg2dewYEWt4ho6mZxu4Dj4HU/3JP+H66+QCsib9wtBJeOrM6jHC1jzKSe1Do53PISn2oAwgClqWDtFyNKx/wQZ6zzFgxPF50ZFsTLXN7Xh73qzZrPNOTinprtWYYTdQnhSpIDWKBS+4aE/Rxy21/L4+K4F46x/Gku9dLrwD7rJ1Zr3PEt85nHX6Ghw33E+zPBPiWVDqGPEu7XRP/oABLCu0VXkMHstxe7JysDycZbeREFr+CqkByAUsrgl7U44i/XtfyCUAk3lq9cv5vp++sCQmG35ZIyHcusd47B5qyNxcDy8BTs37GUvqMJT4UPguDW/kX6Y6vlvAEr9OQ+mHpLQjmZ+5i93jd+AWtk5G/2HeM5qLLp/KEIaFBpzQzC71c=
  on:
    tags: true
    repo: propertybase/react-lds
env:
  global:
  - GITHUB_REPO: propertybase/react-lds
